### ISSUE TITLE
How to generate license from an installer

### ISSUE THREAD

**Issue by sinairv** [dnauck/Portable.Licensing#29]
Hi,
First thanks for this great and easy to use library.

The application I'm trying to release does not have any websites, and the trial edition is supposed to expire in 30 days after installation. 

So I guess the Windows installer is supposed to generate the license file (any alternatives?). To do that I suppose I need to create a console application that generates the license and run it after installation is over. However that program will contain private key and pass phrase embedded into it, which is something I'm trying to avoid. Is there any advice or best practices on how to generate a license as part of Windows installer for apps that don't have a Web API?

**Comment by vbjay** [comment]
Look at using custom actions.

**Comment by dnauck** [comment]
Generating the License file on the client is not an option, because it would require to have also your private key on the client.

You could:
- you have a small website/service that accepts name and email address and creates a 30-day trial license and send it to the client (download, email, etc.) This would also help to check that the same person (by name / email) is not generating every 30 days a new trial license.
- you automatically generate the setup for your product on your server every days and also generate a 30 day trial license with it. But the use could download then every few days a new build with a new 30-day license

**Comment by sinairv** [comment]
Thanks
